config/routes.rb
Rails.application.routes.draw do
  #devise automatic setup on install
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  namespace 'admin' do
    resources :invitations do
      collection do
        get :accept
      end
    end
    resources :customers do
      member do
        put :enable
      end
    end
    resources :services do
      member do
        put :enable
      end
    end
    resources :site_layouts
    resources :appointments do
      collection do
        get :get_events
        get :listing
        get :get_staff
      end
      member do
        get :cancel
        get :set_done
      end
    end
    resources :availabilities do
      collection do
        get :get_services
      end
      member do
        put :enable
      end
    end

    resources :staffs do
      member do
        put :enable
      end
    end
  end

  namespace 'staff' do
    resources :appointments do
      collection do
        get :get_events
      end
      member do
        post :move
        post :resize
        get :cancel
      end
    end
  end

  namespace 'customer' do
    resources :appointments do
      collection do
        get :get_events
        get :get_staff
        get :appointment_history
      end
      member do
        get :cancel
        post :move
        post :resize
        get :cancel_list
      end
    end
  end

  get 'welcome', to: 'welcome#index'
  
  get 'new_signee', to:'welcome#new_signee'
  
end

app/models/service.rb
class Service < ActiveRecord::Base
  acts_as_paranoid
  
  #Associations..................................................
  # FIX- No need to specify join_table
  has_and_belongs_to_many :staffs, :join_table => :services_staffs
  has_many :availabilities
  has_many :appointments

  #Callbacks.....................................................
  # before_destroy :check_associated_availabilities_appointments
  after_destroy :delete_service_from_availability
  
  #Query Interface...............................................
  default_scope { order(:name) }

  #Validations...................................................
  validates :name, uniqueness: { case_sensitive: false }, presence: true

  #Private Methods.................................................
  private

  def delete_service_from_services_staffs
    
  end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController

  PERMITTED_ATTRS = [:name, :slot_window]
  before_action :get_service, only: [:destroy, :enable]
  before_action :get_all_services, only: [:index]

  def index
  end

  def new
    @service = Service.new
  end

  def create

    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.js { render action: 'refresh' }
      else
        format.js { render action: 'new' }
      end
    end
  end

  def destroy

    #if service has any appointment then just disable otherwise really_destroy!
    if @service.appointments.first
      if @service.destroy
        flash[:notice] = 'Service sucessfully disabled. You can now remove its corresponding appointments'
      else
        flash[:error] = 'Service could not be disabled. you have appointments for this service'
      end
    else
      if @service.really_destroy!
        flash[:notice] = 'Service sucessfully permanently deleted'
      else
        flash[:error] = 'Service could not be deleted'
      end
    end

    redirect_to admin_services_path
  end

  def enable
    @service.restore
    flash[:notice] = 'Service is successfully enabled. New appointments for this service can now be created'
    redirect_to admin_services_path
  end

  private

  def get_service
    @service = Service.with_deleted.where(id: params[:id]).first

    if @service
      return @service
    else
      flash[:error] = 'Service not found'
    end
  end

  def service_params
    params.require(:service).permit(*PERMITTED_ATTRS)
  end

  def get_all_services
    @services = Service.with_deleted.paginate page: params[:page], per_page: 10
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service], html: { :'data-remote' => true }  do |f| %>
<% if @service.errors.any? %>
<div id="error_explanation">
    <ul>
      <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Name :' %><br />
    <%= f.text_field :name, value: @service.name %>
  </div>

  <div class="field">
    <%= f.label :slot_window, 'Slot Duration :' %><br />
    <%= f.select(:slot_window, [['15 mins', 15], ['30 mins', 30], ['45 mins', 45], ['60 mins', 60]]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

app/views/admin/services/index.html.erb
<br />
<%= link_to 'Home', welcome_path %>
<br />

<h1>SERVICES</h1>

<%= link_to 'Create New Service', new_admin_service_path, class: 'new-service-link', remote: true %><br /><br />

<table border = '2' width = '500'>
  <tr>
    <th>Service Name</th>
    <th>Duration(in minutes)</th>
    <th>Delete</th>
  </tr>

  <% @services.each do |service| %>
    
    <tr class="<%= service.destroyed? ? 'redify' : 'greenify' %>">

      <td class="list_description">
        <%= service.name %>
      </td>

      <td class="list_description">
        <%= service.slot_window %>
      </td>

      <% if service.destroyed? %>

        <td class="list_actions">
          <%= link_to 'Enable', enable_admin_service_path(service), method: :put %>
        </td>

      <% else %>

        <td>
          <%= link_to 'Disable', admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

      <% end %>

    </tr>
  <% end %>
</table>
<br/>
<%= will_paginate @services %>
<br/>

<div id = 'form-render'>
</div>

app/views/admin/services/new.js.erb
$('#form-render').html("<%==j render 'form' %>");

app/views/admin/services/refresh.js.erb
window.location.href = '/admin/services'