config/routes.rb
Rails.application.routes.draw do
  #devise automatic setup on install
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  namespace 'admin' do
    resources :invitations do
      collection do
        get :accept
      end
    end
    resources :customers do
      member do
        put :enable
      end
    end
    resources :services do
      member do
        put :enable
      end
    end
    resources :site_layouts
    resources :appointments do
      collection do
        get :get_events
        get :listing
        get :get_staff
      end
      member do
        get :cancel
        get :set_done
      end
    end
    resources :availabilities do
      collection do
        get :get_services
      end
      member do
        put :enable
      end
    end

    resources :staffs do
      member do
        put :enable
      end
    end
  end

  namespace 'staff' do
    resources :appointments do
      collection do
        get :get_events
      end
      member do
        post :move
        post :resize
        get :cancel
      end
    end
  end

  namespace 'customer' do
    resources :appointments do
      collection do
        get :get_events
        get :get_staff
        get :appointment_history
      end
      member do
        get :cancel
        post :move
        post :resize
        get :cancel_list
      end
    end
  end

  get 'welcome', to: 'welcome#index'
  
  get 'new_signee', to:'welcome#new_signee'
  
end

app/models/customer.rb
class Customer < User

  #Associations......................................................
  has_many :appointments, foreign_key: 'customer_id'

  #Query Interface....................................................
  default_scope { order(:name) }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  PERMITTED_ATTRS = [:name, :email, :phone_number]
  before_action :find_customer, only: [ :edit, :update, :destroy, :enable ]
  before_action :get_all_customers, only: [:index]

  def index
  end

  def edit
  end

  def destroy

    if @customer.destroy
      flash[:notice] = 'Customer sucessfully deleted'
    else
      flash[:error] = 'Customer could not be deleted'
    end
    redirect_to admin_customers_path
  end

  def update

    respond_to do |format|
      if @customer.update(customer_params)
        format.js { render :action => "refresh" }
      else
        format.js { render :action => "edit" }
      end
    end

  end

  def enable
    @customer.restore
    redirect_to admin_customers_path
  end

  private

  def find_customer

    @customer = Customer.with_deleted.where(id: params[:id]).first

    if @customer
      return @customer
    else
      flash[:error] = 'Customer not found'
    end
  end

  def customer_params
    params.require(:customer)
      .permit(*PERMITTED_ATTRS)
  end

  def get_all_customers
    @customers = Customer.with_deleted.paginate :page => params[:page], :per_page => 10
    @invited_customers = Invitation.all.paginate :page => params[:page], :per_page => 10
  end

end

app/controllers/customer/appointments_controller.rb
class Customer::AppointmentsController < Customer::BaseController
  before_action :get_event, only: [:edit, :update, :destroy, :move, :resize, :cancel_list]
  before_action :get_controller
  before_action :get_services, only: [:index, :new, :update]

  def index
  end

  def new
    @event = Appointment.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @event = Appointment.new(event_params)
    @event.customer_id = current_user.id
    if @event.save
      render nothing: true, status: :created
    else
      render text: @event.errors.full_messages.to_sentence, status: 422
    end
  end

  def get_events

    start_time = Time.at(params[:start].to_i).to_formatted_s(:db)
    end_time   = Time.at(params[:end].to_i).to_formatted_s(:db)

    if params[:staff_id] && params[:service_id]
      appointments = Appointment.for_customer(current_user.id)
                      .where('staff_id = ? and service_id = ?', params[:staff_id], params[:service_id])
                      .by_timerange(start_time, end_time)
    else
      appointments = Appointment.for_customer(current_user.id).by_timerange(start_time, end_time)
    end

    events = []
    appointments.each do |event|
      events << {
                  id: event.id,
                  description: event.description || '',
                  customer: event.customer.name, 
                  start: event.starttime.iso8601,
                  end: event.endtime.iso8601,
                  allDay: false,
                  title: event.title,
                  backgroundColor: event.staff.try(:color),
                  textColor: '#000'
                }
    end
    render json: events.to_json
  end

  def get_staff
    respond_to do |format|
      format.js do
        @staffs = Service.where(id: params[:service_id]).first.try(:staffs)
        render json: @staffs
      end
    end
  end

  def edit
    render json: { form: render_to_string(partial: 'edit_form') }
  end

  def update
    @event.update(event_params)
    render nothing: true
  end

  def destroy
    respond_to do |format|
      format.js do
        @event.update_columns(remark: params[:remark], status: 3)
        flash[:error] = 'Appointment cannot be cancelled' unless @event.destroy
        render nothing: true
      end
      format.html do
        @event.update_columns(remark: params[:appointment][:remark], status: 3)
        flash[:error] = 'Appointment cannot be cancelled' unless @event.destroy
        redirect_to appointment_history_customer_appointments_path
      end
    end

  end

  def appointment_history
    @future_appointments = Appointment.future.where(customer_id: current_user.id).paginate page: params[:page], per_page: 10
    @past_appointments = Appointment.past.where(customer_id: current_user.id).paginate page: params[:page], per_page: 10
  end

  #Customer can move events
  def move
    @event.starttime = make_time_from_minute_and_day_delta(@event.starttime)
    @event.endtime   = make_time_from_minute_and_day_delta(@event.endtime)
    if @event.save
      render nothing: true
    else
      render json: { message: 'This service could not be moved' }
    end
  end

  #Customer can move events
  def resize
    @event.endtime = make_time_from_minute_and_day_delta(@event.endtime)
    if @event.save
      render nothing: true
    else
      render json: { message: 'This service could not be resized' }
    end
  end

  def cancel_list
  end

  private

  def get_event
    @event = Appointment.where(:id => params[:id]).first
    unless @event
      render json: { message: "Appointment Not Found.."}, status: 404 and return
    end
  end

  def event_params
    params.require(:appointment)
      .permit(:staff_id, :service_id, :title, :starttime, :endtime, :status_id, :description, :remark)
  end

  # FIX- Move to helpers
  def get_controller
    @controller_name = params[:controller]
  end

  def get_services
    @services = [['Select', '']]
    Availability.all.uniq(:service_id).each {|av| @services << [av.service.name, av.service_id]}
    @services
  end

  def make_time_from_minute_and_day_delta(event_time)
    params[:minute_delta].to_i.minutes.from_now((params[:day_delta].to_i).days.from_now(event_time))
  end

end

app/controllers/customer/base_controller.rb
class Customer::BaseController < ApplicationController
  layout 'customer'
end

app/views/admin/customers/_form.html.erb
<%= form_for [:admin, @customer], url: admin_customers_path, html: { :'data-remote' => true } do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, 'Name :' %><br />
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email, 'Email :' %><br />
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone_number, 'Phone Number : ' %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/customers/edit.js.erb
$('#form_render').html("<%==j render 'form' %>");
$('#customer_email').prop('readonly', true);

app/views/admin/customers/index.html.erb
<br />
<%= link_to 'Home' , welcome_path %>
<br />

<h2>Customers</h2>

<%= link_to 'New Customer', new_admin_invitation_path(invitee_type: 'Customer'), class: 'new-customer-link', remote: true %><br /><br />

<table border = '2' width = '700'>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Appointments</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @customers.each do |customer| %>
    
    <tr class="<%= customer.destroyed? ? 'redify' : 'greenify' %>">
      <td class="list_description">
        <%= customer.name %>
      </td>

      <td class="list_description">
        <%= customer.email %>
      </td>

      <td class="list_description">
        <%= customer.phone_number %>
      </td>

      <td class="list_description">
        <%= customer.appointments.count %>
      </td>

      <% if customer.destroyed? %>
        <td class="list_actions" colspan = 2 >
          <%= link_to 'Enable', enable_admin_customer_path(customer), method: :put %>
        </td >
      <% else %>
        <td class="list_actions">
          <%= link_to 'Edit', edit_admin_customer_path(customer), remote: true %>
        </td>

        <td class="list_actions">
          <%= link_to 'Disable', admin_customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      <% end %>
  <% end %>

  <% @invited_customers.each do |customer| %>

    <tr class="invitees">
      <td class="list_description">
        <%= customer.name %>
      </td>

      <td class="list_description">
        <%= customer.email %>
      </td>

      <td class="list_description">
        <%= customer.phone_number %>
      </td>

      <td class="list_description">
        NA
      </td>

      <td class="list_actions" colspan = 2 >
        NA
      </td>

    </tr>
  <% end %>

</table>
<br/>
<%= will_paginate @customers %>
<br/>

<div id = 'form_render'>
</div>

app/views/admin/customers/refresh.js.erb
window.location.href = '/admin/customers'

app/views/admin/customers/search.html.erb
<%= form_tag(search_customers_path, method: "get") do %>
  <fieldset>
    <legend>Search Customer</legend>
    <%= label_tag :search_phone, 'Search customer by phone number :' %>
    <%= search_field(:customer, :phone_number) %>
    <%= submit_tag 'Search' %>
    <% if(@found_customer) %>
      <fieldset>
        <legend>Found Customer</legend>
        <%= label_tag :found_name, 'Name : ' + @found_customer.name.to_s %><br />
        <%= label_tag :found_phone_number, 'Phone Number : ' + @found_customer.phone_number.to_s %><br />
        <%= label_tag :found_address, 'Address : ' + @found_customer.address.to_s %><br />
        <%= label_tag :found_email, 'Email : ' + @found_customer.email.to_s %><br />
        <%= link_to 'Create New Appointment', new_appointment_path(found_customer_id: @found_customer), method: :get %>
        <% @found_customer = nil %>
    <% else %>
      <%= link_to 'Register Customer', new_customer_path, method: :get %>
    <% end %>
      </fieldset>
    <br />
  </fieldset>
<% end %>

app/views/admin/customers/show.html.erb
<div>
  <%= link_to 'Create New Appointment', new_appointment_path(found_patient_id: @new_patient), method: :get %>
</div>