config/routes.rb
Rails.application.routes.draw do
  #devise automatic setup on install
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  namespace 'admin' do
    resources :invitations do
      collection do
        get :accept
      end
    end
    resources :customers do
      member do
        put :enable
      end
    end
    resources :services do
      member do
        put :enable
      end
    end
    resources :site_layouts
    resources :appointments do
      collection do
        get :get_events
        get :listing
        get :get_staff
      end
      member do
        get :cancel
        get :set_done
      end
    end
    resources :availabilities do
      collection do
        get :get_services
      end
      member do
        put :enable
      end
    end

    resources :staffs do
      member do
        put :enable
      end
    end
  end

  namespace 'staff' do
    resources :appointments do
      collection do
        get :get_events
      end
      member do
        post :move
        post :resize
        get :cancel
      end
    end
  end

  namespace 'customer' do
    resources :appointments do
      collection do
        get :get_events
        get :get_staff
        get :appointment_history
      end
      member do
        get :cancel
        post :move
        post :resize
        get :cancel_list
      end
    end
  end

  get 'welcome', to: 'welcome#index'
  
  get 'new_signee', to:'welcome#new_signee'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize, only: [:new_signee]

  def new_signee
  end

  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<% case current_user.type %>
  <% when 'Customer' %>
    <div class = 'welcome-links'>
      <%= link_to 'Book Appointments', customer_appointments_path %>
      <%= link_to 'Appointment History', appointment_history_customer_appointments_path %>
    </div>
  <% when 'Staff' %>
    <div class = 'welcome-links'>
      <%= link_to 'Appointment', staff_appointments_path %>
    </div>
  <% when 'Admin' %>
    <div class = 'welcome-links'>
      <%= link_to 'Appointment(Calendar View)', admin_appointments_path %>
      <%= link_to 'Appointment(List View)', listing_admin_appointments_path %>
      <%= link_to 'Services', admin_services_path %>
      <%= link_to 'Availabilities', admin_availabilities_path %>
      <%= link_to 'Staff', admin_staffs_path %>
      <%= link_to 'Upload Logo', edit_admin_site_layout_path(current_layout) %>
      <%= link_to 'Customers', admin_customers_path %>
    </div>
<% end %>

app/views/welcome/new_sign_up.html.erb
<h2>Thankyou for registering with us!!!!</h2>

<h5>Please confirm ur email through the link sent to your EmailID</h5>

<%= link_to 'Resend Confirmation mail', new_user_confirmation_path %>

app/views/welcome/new_signee.html.erb
<h2>Thank you for registering with us!!!!</h2>

<h5>Please confirm your email through the link sent to your EmailID</h5>

<%= link_to 'Resend Confirmation mail', new_user_confirmation_path %><br />

<%= link_to 'Log In', '/' %>