config/routes.rb
Rails.application.routes.draw do
  #devise automatic setup on install
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  namespace 'admin' do
    resources :invitations do
      collection do
        get :accept
      end
    end
    resources :customers do
      member do
        put :enable
      end
    end
    resources :services do
      member do
        put :enable
      end
    end
    resources :site_layouts
    resources :appointments do
      collection do
        get :get_events
        get :listing
        get :get_staff
      end
      member do
        get :cancel
        get :set_done
      end
    end
    resources :availabilities do
      collection do
        get :get_services
      end
      member do
        put :enable
      end
    end

    resources :staffs do
      member do
        put :enable
      end
    end
  end

  namespace 'staff' do
    resources :appointments do
      collection do
        get :get_events
      end
      member do
        post :move
        post :resize
        get :cancel
      end
    end
  end

  namespace 'customer' do
    resources :appointments do
      collection do
        get :get_events
        get :get_staff
        get :appointment_history
      end
      member do
        get :cancel
        post :move
        post :resize
        get :cancel_list
      end
    end
  end

  get 'welcome', to: 'welcome#index'
  
  get 'new_signee', to:'welcome#new_signee'
  
end

app/models/availability.rb
class Availability < ActiveRecord::Base
  acts_as_paranoid
  
  # Associations.................................................
  belongs_to :service
  # has_and_belongs_to_many :services
  belongs_to :staff

  # Validations..................................................
  validates :start_time, :end_time, :start_date, :end_date, :service_id, :staff_id, presence: true
  validate :time_period, on: [:create, :edit]
  validate :for_future, on: [:create, :edit]
  validate :busy, on: [:create, :edit]

  #Query Interface...............................................
  default_scope { order('deleted_at asc') }

  #Public methods................................................

  def overlapping_with?(starts_at, ends_at)

    (((start_time).between?(starts_at, ends_at)) || ((end_time).between?(starts_at, ends_at)) || 
        ((starts_at).between?(start_time, end_time)) || ((ends_at).between?(start_time, end_time)))
  end

  #Private methods................................................
  private

  def time_period
    errors[:base] = 'Invalid time period chosen' unless (start_time < end_time) && (start_date <= end_date)
  end

  def for_future
    start_time_in_sec = (start_time.hour * 3600) + (start_time.min * 60)
    time_now_in_sec = (Time.now.hour * 3600) + (Time.now.min * 60)
    errors[:base] = 'Availability cannot be booked for past dates' if ((start_date < Date.today) || (start_date == Date.today && start_time_in_sec < time_now_in_sec))
  end

  def busy
    #staff and time pair should be unique
    day_begin = start_time.beginning_of_day()
    day_end = start_time.end_of_day()
    avaialability_starts_at = start_time
    avaialability_ends_at = end_time
    schedule_list = self.class.where('staff_id = ? and service_id = ? and start_time between ? and ?', staff_id, service_id, day_begin, day_end)
    overlapping = schedule_list.any? { |availability| availability.overlapping_with?(avaialability_starts_at, avaialability_ends_at) }
    self.errors[:base] = " #{ self.staff.name.capitalize } is busy for this time period " if overlapping

  end

end

app/models/staff.rb
class Staff < User

  #Constants.......................................................
  COLORS = ['#D7FF00', '#FF9B00', '#39FF00', '#FF00A4','#0051FF', '#00F3FF', '#6A00FF', '#FF002A', '#FBFF00']

  #Associations......................................................
  has_many :appointments, foreign_key: 'staff_id'
  has_and_belongs_to_many :services, :join_table => :services_staffs
  has_many :availabilities

  #Query Interface....................................................
  default_scope { order(:name) }

  #Validations........................................................
  validates_presence_of :services

  #Callbacks..........................................................
  before_create :generate_password
  before_create :assing_color
  after_create :send_welcome_email
  after_destroy :remove_availability

  private

  def remove_availability
    active_availabilities = availabilities.where('end_time > ?', Date.today)
    active_availabilities.each { |avail| avail.really_destroy! }
  end

  def generate_password
    self.password = SecureRandom.urlsafe_base64(5)
  end

  def send_welcome_email
    StaffWelcomeMailer.welcome_email(self).deliver
  end

  def assing_color
    self.color = COLORS.sample
  end

end

app/controllers/admin/availabilities_controller.rb
class Admin::AvailabilitiesController < Admin::BaseController

  # PERMITTED_ATTRS = [{ service_ids: [] }, :staff_id, :start_time, :end_time, :start_date, :end_date]
  PERMITTED_ATTRS = [:service_id, :staff_id, :start_time, :end_time, :start_date, :end_date]
  before_action :get_availability, only: [:update, :destroy, :enable]
  before_action :get_staffs, only: [:new]
  before_action :get_all_availabilities, only: [:index]

  def index
  end

  def new
    @availability = Availability.new
  end

  def create

    @availability = Availability.new(availability_params)

    if @availability.save
      render 'refresh'
    else
      get_staffs
      @services = @availability.staff.services
      render action: 'new'
    end
  end

  def destroy
    if @availability.destroy
      flash[:notice] = 'Availability sucessfully deleted'
    else
      flash[:error] = 'Availability could not be deleted'
    end
    redirect_to admin_availabilities_path
  end

  def update
    if @availability.update(availability_params)
      render 'refresh'
    else
      format.js do
        render 'edit'
      end
    end
  end

  def enable
    @availability.restore
    redirect_to admin_availabilities_path
  end

  #fetches all the services corresponding to a staff
  def get_services
    respond_to do |format|
      format.js do
        @services = Staff.where(id: params[:staff_id]).first.services
        render json: @services
      end
    end
  end

  private

  def get_availability
    @availability = Availability.with_deleted.where(id: params.require(:id)).first

    @availability ||= (flash[:error] = 'Availability not found')
  end

  def availability_params
    params.require(:availability)
      .permit(*PERMITTED_ATTRS)
  end

  def get_staffs
    @staff = Staff.all
  end

  def get_all_availabilities
    @availabilities = Availability.with_deleted.where('end_date >= ?', Date.today).paginate page: params[:page], per_page: 10
  end
end

app/helpers/availability_helper.rb
module AvailabilityHelper

end

app/views/admin/availabilities/_form.html.erb
<%= form_for [:admin, @availability], html: { :'data-remote' => true } do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @availability.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staff_id, 'Staff :' %><br />
    <%= f.collection_select(:staff_id, @staff, :id, :name, {:prompt => 'Select'}) %>
  </div>

  <div class="field">
    <%= f.label :service_id, 'Service :' %><br />
    <%= f.collection_select(:service_id, @services || [], :id, :name, {:prompt => 'Select'}) %>
    <%#= f.collection_select(:service_id, @services || [], :id, :name, { name: 'availability[service_ids][]'}, multiple: true) %>
  </div>

  <div class="field">
    <%= f.label :start_time, 'Date(From) :' %><br />
    <%= date_field(:availability, :start_date) %> 
  </div>

  <div class="field">
    <%= f.label :start_time, 'Date(To) :' %><br />
    <%= date_field(:availability, :end_date) %>
  </div>

  <div class="field">
    <%= f.label :start_time, 'Time(From) :' %><br />
    <%= time_field(:availability, :start_time) %>
  </div>

  <div class="field">
    <%= f.label :end_time, 'Time(To) :' %><br />
    <%= time_field(:availability, :end_time) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/availabilities/index.html.erb
<%= stylesheet_link_tag :availability %>

<br />
<%= link_to 'Home' , welcome_path %>
<br />
<h2>Availabilities</h2>

<%= link_to 'New Availability', new_admin_availability_path, class: 'new-availability-link', remote: true %><br /><br />

<table>
  <tr>
    <th>Staff</th>
    <th>Service</th>
    <th>Date(from)</th>
    <th>Date(to)</th>
    <th>Time(from)</th>
    <th>Time(to)</th>
    <th>Action</th>
  </tr>

  <% @availabilities.each do |availability| %>
    
    <tr class="<%= availability.destroyed? ? 'redify' : 'greenify' %>">
      <td class="list_description">
        <%= availability.staff.name %>
      </td>
      <td class="list_description">
        <%#= ((availability.services).map{|service| service.name}).join(',') %>
        <%= availability.service.name %>
      </td>
      <td class="list_description">
        <%= availability.start_date %>
      </td>
      <td class="list_description">
        <%= availability.end_date %>
      </td>
      <td class="list_description">
        <%= availability.start_time.strftime("%I:%M %p") %>
      </td>
      <td class="list_description">
        <%= availability.end_time.strftime("%I:%M %p") %>
      </td>
      <% if availability.destroyed? %>
        <td class="list_actions">
          <%= link_to 'Enable', enable_admin_availability_path(availability), method: :put %>
        </td>
      <% else %>
        <td>
          <%= link_to 'Disable', admin_availability_path(availability), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<br/>
<%= will_paginate @availabilities %>
<br />

<div class = 'new-availability-container'>
  <div id="form_render">
  </div>
</div>

app/views/admin/availabilities/new.js.erb
$('#form_render').html("<%==j render 'form' %>");

$('#availability_staff_id').on('change', function(){
  var staff_id = $('#availability_staff_id').val();
  $.ajax({
    type: 'get',
    data: '&staff_id=' + staff_id,
    async: true,
    dataType: 'json',
    url: "/admin/availabilities/get_services",
    success: function(services, status, xhr) {

      var selectbox = $('#availability_service_id');
      selectbox.empty();
      $.each (services, function(index, service) {
        option = $("<option />").attr({value: service.id}).text(service.name)
        selectbox.append(option);
      })
    },
    error: function() {}
  });

});

// $('#availability_service_id').select2({
//   placeholder: "Select Services...", width: '199px'
// });

app/views/admin/availabilities/refresh.js.erb
window.location.href = '/admin/availabilities'